AWSTemplateFormatVersion: "2010-09-09"
Description: Web ACL with AWS Managed Rules for App Runner

Resources:
  MyWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: nv-balto-waf-flaskapp
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: nv-balto-apprunner-waf-metric
        SampledRequestsEnabled: true
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: common-rules
            SampledRequestsEnabled: true

        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: sql-injection-rules
            SampledRequestsEnabled: true

        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: bad-input-rules
            SampledRequestsEnabled: true

  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref AppRunnerServiceArn
      WebACLArn: !GetAtt MyWebACL.Arn

Parameters:
  AppRunnerServiceArn:
    Type: String
    Description: ARN of the AWS App Runner service to associate with the Web ACL
